# Generated by Django 3.1.7 on 2021-03-02 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20210228_0811'),
    ]

    operations = [
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('bday', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('face_data', models.CharField(blank=True, max_length=25)),
                ('fingerprint', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.DeleteModel(
            name='Jurusan',
        ),
        migrations.DeleteModel(
            name='Kelas',
        ),
    ]
