# Generated by Django 3.1.7 on 2021-03-02 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('A_WEB', '0004_userc_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='certificate',
            old_name='nik',
            new_name='cuser',
        ),
    ]
