# Generated by Django 3.1.7 on 2021-03-02 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20210302_1108'),
        ('A_WEB', '0006_auto_20210302_0931'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.cuser'),
        ),
        migrations.DeleteModel(
            name='CUser',
        ),
    ]
