# Generated by Django 3.1.7 on 2021-03-02 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('A_WEB', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(max_length=10)),
                ('nik', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='A_WEB.userc')),
            ],
        ),
        migrations.DeleteModel(
            name='State',
        ),
    ]
