# Generated by Django 3.1.7 on 2021-03-02 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_WEB', '0002_auto_20210302_0845'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='note',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
