# Generated by Django 3.1.7 on 2021-03-02 09:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_WEB', '0003_certificate_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='userc',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
