# Generated by Django 3.1.7 on 2021-03-02 09:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('A_WEB', '0005_auto_20210302_0928'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userc',
            name='date',
        ),
        migrations.AddField(
            model_name='certificate',
            name='date',
            field=models.DateField(blank=True, default=datetime.date.today),
        ),
    ]
