# Generated by Django 3.0.5 on 2021-02-12 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('his_nik', models.CharField(max_length=100)),
                ('his_name', models.CharField(max_length=100)),
                ('his_sertifikat', models.CharField(max_length=20)),
                ('his_result', models.IntegerField()),
            ],
        ),
    ]
