# Generated by Django 3.1.7 on 2021-03-06 07:51

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=250)),
                ('date', models.DateField(blank=True, default=datetime.date.today)),
                ('result', models.BooleanField(default=True)),
                ('good_result', models.BooleanField(default=False)),
                ('a_place', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SETH.aplace')),
            ],
        ),
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('bday', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('password', models.CharField(default='12345', max_length=50)),
                ('face_data', models.CharField(blank=True, max_length=25)),
                ('fingerprint', models.CharField(blank=True, max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('passed', models.BooleanField(default=False)),
                ('cert', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETH.certificate')),
            ],
        ),
        migrations.AddField(
            model_name='certificate',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETH.cuser'),
        ),
        migrations.CreateModel(
            name='BPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('supported_certs', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETH.certificate')),
            ],
        ),
    ]
