# Generated by Django 3.1.7 on 2021-03-21 04:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplace', to='SETH.aplace')),
            ],
        ),
        migrations.CreateModel(
            name='BPlace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('supported_certs', models.CharField(default='Genose', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bplace', to='SETH.bplace')),
            ],
        ),
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('bday', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('password', models.CharField(default='12345', max_length=50)),
                ('face_data', models.BooleanField(default=False)),
                ('fingerprint', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('usertype', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A_TYPE'), (2, 'B_TYPE'), (3, 'C_TYPE')], null=True)),
                ('auser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SETH.auser')),
                ('buser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SETH.buser')),
                ('cuser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SETH.cuser')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
                ('passed', models.BooleanField(default=False)),
                ('b_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SETH.bplace')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETH.cuser')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cert_type', models.CharField(max_length=10)),
                ('note', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(blank=True, default=datetime.date.today, null=True)),
                ('result', models.BooleanField(default=True)),
                ('good_result', models.BooleanField(default=False)),
                ('a_place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='SETH.aplace')),
                ('cuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETH.cuser')),
            ],
        ),
    ]
