# Generated by Django 3.1.7 on 2021-03-06 09:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('bplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buser', to='SETH.bplace')),
            ],
        ),
        migrations.CreateModel(
            name='AUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('aplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auser', to='SETH.aplace')),
            ],
        ),
    ]
