# Generated by Django 3.1.7 on 2021-03-21 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Gadjah Mada University', max_length=100)),
                ('place_id', models.CharField(default='Gadjah Mada University', max_length=100)),
                ('is_aplace', models.BooleanField(default=False)),
                ('is_bplace', models.BooleanField(default=False)),
                ('aplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplace_place', to='SETH.aplace')),
                ('bplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bplace_place', to='SETH.bplace')),
            ],
        ),
    ]
