# Generated by Django 3.1.7 on 2021-03-10 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0002_auto_20210309_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserType',
            fields=[
                ('id', models.PositiveSmallIntegerField(choices=[(1, 'A_TYPE'), (2, 'B_TYPE'), (3, 'C_TYPE')], primary_key=True, serialize=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='commonuser',
            name='usertype',
        ),
        migrations.AddField(
            model_name='commonuser',
            name='usertype',
            field=models.ManyToManyField(to='SETH.UserType'),
        ),
    ]
