# Generated by Django 3.1.7 on 2021-03-10 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0003_auto_20210310_0147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonuser',
            name='usertype',
            field=models.ManyToManyField(blank=True, null=True, to='SETH.UserType'),
        ),
    ]
