# Generated by Django 3.1.7 on 2021-03-21 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0003_place_formatted_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='place_id',
            new_name='place_gcp_id',
        ),
    ]
