# Generated by Django 3.1.7 on 2021-03-21 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0004_auto_20210321_0803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='aplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='aplace_place', to='SETH.aplace'),
        ),
        migrations.AlterField(
            model_name='place',
            name='bplace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bplace_place', to='SETH.bplace'),
        ),
    ]
