# Generated by Django 3.1.7 on 2021-03-10 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0004_auto_20210310_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAuthentication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='username')),
                ('password', models.CharField(max_length=30, verbose_name='password')),
                ('usertype', models.ManyToManyField(blank=True, null=True, to='SETH.UserType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('bday', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('postalcode', models.CharField(max_length=50)),
                ('password', models.CharField(default='12345', max_length=50)),
                ('face_data', models.CharField(blank=True, max_length=25, null=True)),
                ('fingerprint', models.CharField(blank=True, max_length=25, null=True)),
                ('authentication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('authentication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommonUser', to='SETH.bplace')),
            ],
        ),
        migrations.CreateModel(
            name='AUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='CommonUser', to='SETH.aplace')),
                ('authentication', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='certificate',
            name='cuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SETH.cuser'),
        ),
        migrations.DeleteModel(
            name='CommonUser',
        ),
    ]
