# Generated by Django 3.1.7 on 2021-03-10 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0006_auto_20210310_0208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userauthentication',
            name='usertype',
        ),
        migrations.AddField(
            model_name='userauthentication',
            name='usertype',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'A_TYPE'), (2, 'B_TYPE'), (3, 'C_TYPE')], null=True),
        ),
        migrations.DeleteModel(
            name='UserType',
        ),
    ]
