# Generated by Django 3.1.7 on 2021-03-10 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0007_auto_20210310_0215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auser',
            name='aplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplace', to='SETH.aplace'),
        ),
        migrations.AlterField(
            model_name='buser',
            name='bplace',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bplace', to='SETH.bplace'),
        ),
    ]
