# Generated by Django 3.1.7 on 2021-03-20 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0008_auto_20210310_0332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cuser',
            name='fingerprint',
        ),
        migrations.AlterField(
            model_name='cuser',
            name='face_data',
            field=models.BooleanField(default=False),
        ),
    ]
