# Generated by Django 3.1.7 on 2021-03-20 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SETH', '0009_auto_20210320_0229'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuser',
            name='fingerprint',
            field=models.BooleanField(default=False),
        ),
    ]
